#!/bin/sh

set -e

# This uses gox from https://github.com/mitchellh/gox
# Make sure you've run gox -build-toolchain

if [ "$1" == "" ]; then
    echo "Syntax: $0 Version"
    exit 1
fi
VERSION="$1"

rm -rf build

gox -output "build/{{.Dir}}-${VERSION}-{{.OS}}-{{.Arch}}/{{.Dir}}"

mv build/snapshot-manager-${VERSION}-darwin-amd64 build/snapshot-manager-${VERSION}-osx-amd64
mv build/snapshot-manager-${VERSION}-darwin-386 build/snapshot-manager-${VERSION}-osx-386

cd build

for d in `ls`; do
    cp -a ../README.txt $d/
    cp -a ../README.html $d/
    cp -a ../snapshot-manager.1 $d/
    zip -r9 $d.zip $d
    rm -rf $d
done

cd ..
