#!/bin/bash
#
# Upload a release

set -e

REPO="snapshot-manager"

if [ "$1" == "" ]; then
    echo "Syntax: $0 Version"
    exit 1
fi
VERSION="$1"
if [ "$GITHUB_USER" == "" ]; then
   echo 1>&2 "Need GITHUB_USER environment variable"
   exit 1
fi
if [ "$GITHUB_TOKEN" == "" ]; then
   echo 1>&2 "Need GITHUB_TOKEN environment variable"
   exit 1
fi

echo "Making release ${VERSION}"
github-release release \
    --repo ${REPO} \
    --tag ${VERSION} \
    --name "Snapshot Manager" \
    --description "Tool to upload and download Memset snapshots"

for build in `ls build`; do
    echo "Uploading ${build}"
    base="${build%.*}"
    parts=(${base//-/ })
    os=${parts[3]}
    arch=${parts[4]}

    github-release upload \
        --repo ${REPO} \
        --tag ${VERSION} \
        --name "${build}" \
        --file build/${build}
done

github-release info \
    --repo ${REPO} \
    --tag ${VERSION}

echo "Done"
